name: Discord powiadomienie o nowym commicie

on:
  push:
    branches:
      - main

jobs:
    Wyslanie-powiadomienia:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Instalacja dependencji
        run: pip install logging typing dotenv requests
        
      - name: Wysyłanie powiadomienia na Discord
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REF: ${{ github.ref }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          MODIFIED_FILES_JSON: ${{ toJson(github.event.head_commit.modified) }}
          
        run: python .github/Skrypty/discord-powiadomienie.py
